name: history_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## -- STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1

  ## -- ICON PACKAGES
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  ## -- OnBoarding PACKAGES
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.5

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3

  connectivity_plus: ^5.0.2
  percent_indicator: ^4.2.3
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  #-----------LOCAL ASSETS-----------#
  assets:
    - assets/logos/
    - assets/lottie/
    - assets/images/buttons/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/icons/create_account/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

