// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Әдепкі негізгі опциялар веб үшін конфигурацияланбаған - '
            'FlutterFire CLI қайта іске қосу арқылы мұны қайта конфигурациялауға болады.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'Әдепкі негізгі опциялар веб үшін конфигурацияланбаған - '
              'FlutterFire CLI қайта іске қосу арқылы мұны қайта конфигурациялауға болады.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Әдепкі негізгі опциялар веб үшін конфигурацияланбаған - '
              'FlutterFire CLI қайта іске қосу арқылы мұны қайта конфигурациялауға болады.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Әдепкі негізгі опциялар веб үшін конфигурацияланбаған - '
              'FlutterFire CLI қайта іске қосу арқылы мұны қайта конфигурациялауға болады.',
        );
      default:
        throw UnsupportedError(
          'Бұл платформа үшін әдепкі негізгі опцияларға қолдау көрсетілмейді.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJzEa1hBUX7Qag8oF06B1ChcqgpU3I9Q',
    appId: '1:170390610312:android:f4aa4b04180d8708135a3d',
    messagingSenderId: '170390610312',
    projectId: 'history-app-777',
    storageBucket: 'history-app-777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCov9ogqxk_lHDbB5-z57qDen7bdqFjVik',
    appId: '1:170390610312:ios:9e07dadcef9843dd135a3d',
    messagingSenderId: '170390610312',
    projectId: 'history-app-777',
    storageBucket: 'history-app-777.appspot.com',
    iosBundleId: 'com.krmeiirbek.historyApp',
  );
}
